version: '3'
services:
  python3:
    restart: always
    build: .
    command: >
      bash -c "
      pip install -r requirements.txt &&
      python3 src/main.py
      "
    container_name: 'python3'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./:/root/