version: '3'
services:
  python3:
    restart: always
    build: .
    command: >
      bash -c "pip install -r src/requirements.txt &&
      python3 src/main.py"
    container_name: 'python3'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./src:/root/src
      - ./logs:/root/logs